services:
  - type: web
    name: vite-react-typescript-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production 